#!/usr/bin/env bash

################################################################################
# Runs pytest on the repository.
#
# Usage:
#     check/pytest [--flags]
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

# Run pytest
pytest "$@" examples --nb-test-files --ignore=examples/aqt_compile.ipynb --ignore=examples/finance.ipynb --ignore=examples/ibmq_compile.ipynb
